"""
Portfolio generator.

Reads:
    portfolio-data/profile.json
    portfolio.yml files from your GitHub repositories

Generates:
    js/config.js

IMPORTANT:
    This script NEVER reads or modifies README.md files.
"""

import json
import base64
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import HTTPError

import yaml


# ============================================================
# SETTINGS
# ============================================================

GITHUB_USERNAME = "Asad-Khan710"

ROOT = Path(__file__).resolve().parent.parent

PROFILE_FILE = ROOT / "portfolio-data" / "profile.json"
OUTPUT_FILE = ROOT / "js" / "config.js"


# ============================================================
# GITHUB API
# ============================================================

def github_request(url):
    """Make a read-only request to GitHub's public API."""

    request = Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "Asad-Khan710-Portfolio-Automation"
        }
    )

    with urlopen(request) as response:
        return json.loads(response.read().decode("utf-8"))


def get_repositories():
    """Get repositories belonging to the GitHub account."""

    url = (
        f"https://api.github.com/users/"
        f"{GITHUB_USERNAME}/repos"
        f"?type=owner&per_page=100"
    )

    print(f"Connecting to GitHub: {GITHUB_USERNAME}")

    return github_request(url)


def get_portfolio_file(repo):
    """
    Look for portfolio.yml in the root of a repository.

    README.md is deliberately NOT requested.
    """

    owner = repo["owner"]["login"]
    name = repo["name"]

    url = (
        f"https://api.github.com/repos/"
        f"{owner}/{name}/contents/portfolio.yml"
    )

    try:
        return github_request(url)

    except HTTPError as error:
        if error.code == 404:
            return None

        raise


# ============================================================
# PROJECT PROCESSING
# ============================================================

def load_project(repo, portfolio_file):
    """Convert portfolio.yml into the format used by config.js."""

    encoded_content = portfolio_file["content"]
    decoded_content = base64.b64decode(encoded_content).decode("utf-8")

    data = yaml.safe_load(decoded_content)

    if not data:
        return None

    project = {
        "title": data.get("title", repo["name"]),
        "difficulty": data.get("difficulty", "medium"),
        "desc": data.get("description", repo.get("description") or ""),
        "tags": data.get("tags", []),

        # GitHub URL is automatically taken from the repository.
        "link": repo["html_url"],

        "details": {
            "approach": data.get("approach", ""),
            "tools": data.get("tools", []),
            "learnings": data.get("learnings", "")
        }
    }

    return project


def find_projects():
    """Find all GitHub repositories containing portfolio.yml."""

    repositories = get_repositories()

    projects = []

    print(f"Repositories found: {len(repositories)}")
    print("\nChecking repositories for portfolio.yml...\n")

    for repo in repositories:

        # Ignore forks.
        if repo.get("fork"):
            continue

        print(f"Checking: {repo['name']}")

        portfolio_file = get_portfolio_file(repo)

        if portfolio_file is None:
            continue

        print(f"  -> portfolio.yml FOUND")

        project = load_project(repo, portfolio_file)

        if project:
            projects.append(project)

    return projects


# ============================================================
# PROFILE
# ============================================================

def load_profile():
    """Load global portfolio information."""

    with open(PROFILE_FILE, "r", encoding="utf-8") as file:
        return json.load(file)


# ============================================================
# CONFIG GENERATION
# ============================================================

def javascript_value(value):
    """Convert Python data into valid JavaScript data."""

    return json.dumps(
        value,
        indent=2,
        ensure_ascii=False
    )


def generate_config(profile, projects):

    config = profile.copy()

    # Replace the projects section with
    # projects discovered from GitHub.
    config["projects"] = projects

    javascript = (
        "/* ============================================================\n"
        "   GENERATED FILE — DO NOT EDIT MANUALLY\n"
        "   Generated by automation/sync.py\n"
        "\n"
        "   Edit:\n"
        "   - portfolio-data/profile.json\n"
        "   - project repositories' portfolio.yml files\n"
        "\n"
        "   README.md files are NEVER modified by this automation.\n"
        "   ============================================================ */\n\n"
        "const CONFIG = "
        + javascript_value(config)
        + ";\n"
    )

    with open(OUTPUT_FILE, "w", encoding="utf-8") as file:
        file.write(javascript)


# ============================================================
# MAIN
# ============================================================

def main():

    print("====================================")
    print("      PORTFOLIO SYNC")
    print("====================================")

    print("\nLoading profile...")

    profile = load_profile()

    print("\nSearching GitHub for projects...")

    projects = find_projects()

    print(f"\nProjects found: {len(projects)}")

    print("\nGenerating config.js...")

    generate_config(profile, projects)

    print("\nDone.")
    print(f"Updated: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()